import "../styles/globals.css";
import type { AppProps } from "next/app";
import Head from "next/head";
import { description, keywords, Meta, title } from "../components/SEO/Meta";

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Component {...pageProps} />
      <Head>
        {/* <title>MSJCS Club</title> */}
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/favicon.ico" />
        <meta name="keywords" content={keywords} />
        <link rel="apple-touch-icon" sizes="180x180" href="/images/logo.png" />
        <link rel="icon" type="image/svg+xml" href="/images/logo.png" />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/images/logo.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/images/logo.png"
        />
        {/* <link rel="mask-icon" href="/images/logo.png" color="#5bbad5" />
        <meta name="msapplication-TileColor" content="#da532c" /> */}
        <meta name="theme-color" content="#000000" />
        <meta property="og:image" content="/images/logo.png" />
        <meta property="og:title" content={title} />
        <meta property="og:description" content={description} />

        <meta name="description" content={description} />

        <Meta />
      </Head>
    </>
  );
}

export default MyApp;
