import type { NextPage } from "next";
import Head from "next/head";
import { Hero } from "../components/Hero";
import { Info } from "../components/Info";
import { Haiku } from "../components/Haiku";
import { Discord } from "../components/Discord";
import { Navbar } from "../components/Navbar";

import styles from "../styles/About.module.css";
import { AboutCard } from "../components/About/AboutCard";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className={styles.special_padding}>
        <h1>About Us</h1>
        <p>
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error,
          consectetur sequi sit accusantium vitae vero animi, id sed odio modi
          doloremque quod! Eligendi nobis officiis tempora facere natus?
          Laboriosam, eligendi?
        </p>

        <div className={styles.grid}>
          <AboutCard
            name="Eggos"
            role="Chief Egg Master"
            description="Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit nobis earum, sed quisquam reprehenderit iusto saepe alias enim beatae, nam laborum dignissimos, quibusdam repellat placeat molestiae distinctio facilis doloribus tenetur!"
          />
          <AboutCard
            name="Eggos"
            role="Chief Egg Master"
            description="Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit nobis earum, sed quisquam reprehenderit iusto saepe alias enim beatae, nam laborum dignissimos, quibusdam repellat placeat molestiae distinctio facilis doloribus tenetur!"
          />
          <AboutCard
            name="Eggos"
            role="Chief Egg Master"
            description="Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit nobis earum, sed quisquam reprehenderit iusto saepe alias enim beatae, nam laborum dignissimos, quibusdam repellat placeat molestiae distinctio facilis doloribus tenetur!"
          />
          <AboutCard
            name="Eggos"
            role="Chief Egg Master"
            description="Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit nobis earum, sed quisquam reprehenderit iusto saepe alias enim beatae, nam laborum dignissimos, quibusdam repellat placeat molestiae distinctio facilis doloribus tenetur!"
          />
          <AboutCard
            name="Eggos"
            role="Chief Egg Master"
            description="Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit nobis earum, sed quisquam reprehenderit iusto saepe alias enim beatae, nam laborum dignissimos, quibusdam repellat placeat molestiae distinctio facilis doloribus tenetur!"
          />
          <AboutCard
            name="Eggos"
            role="Chief Egg Master"
            description="Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit nobis earum, sed quisquam reprehenderit iusto saepe alias enim beatae, nam laborum dignissimos, quibusdam repellat placeat molestiae distinctio facilis doloribus tenetur!"
          />
        </div>
      </div>
    </div>
  );
};

export default Home;
